services:
  - type: web
    name: erp-universite-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 3000
